/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-02-18 10:36:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta\r\n");
      out.write("      name=\"viewport\"\r\n");
      out.write("      content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"icon\" href=\"login-form/images/people.png\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fonts/icomoon/style.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"login-form/css/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"login-form/css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <title>Coding Wallah</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"content\" style=\"height: 93vh\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        Welcome to <span style=\"font-weight: 700\">Coding Wallah</span> Institute\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 order-md-2\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"assets/img/login.jpg\"\r\n");
      out.write("              alt=\"Image\"\r\n");
      out.write("              class=\"img-fluid\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 contents\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("              <div class=\"col-md-8\">\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("                  <h3>Log In to <strong>Admin</strong></h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p style=\"color:red\"></p>\r\n");
      out.write("                <form action=\"LoginAuthentication\" method=\"get\">\r\n");
      out.write("                  <div class=\"form-group first\">\r\n");
      out.write("                    <label for=\"username\">Username</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"username\" name=\"Username\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group last mb-4\">\r\n");
      out.write("                    <label for=\"password\">Password</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"id_password\" name=\"Password\"/>\r\n");
      out.write("                    <i\r\n");
      out.write("                      class=\"far fa-eye-slash\"\r\n");
      out.write("                      id=\"togglePassword\"\r\n");
      out.write("                      style=\"\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        float: right;\r\n");
      out.write("                        margin-top: -35px;\r\n");
      out.write("                        position: relative;\r\n");
      out.write("                      \"\r\n");
      out.write("                    ></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"submit\"\r\n");
      out.write("                    value=\"Log In\"\r\n");
      out.write("                    class=\"btn text-white btn-block btn-primary\"\r\n");
      out.write("                  />\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <footer\r\n");
      out.write("        style=\"\r\n");
      out.write("          display: flex;\r\n");
      out.write("          justify-content: center;\r\n");
      out.write("          position: sticky;\r\n");
      out.write("          background-color: #38d39f;\r\n");
      out.write("          padding: 10px 10px;\r\n");
      out.write("          margin-top: 8px;\r\n");
      out.write("        \"\r\n");
      out.write("      >\r\n");
      out.write("        @Copyright | Coding Wallah | 2022- All Right Reserved.\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"login-form/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"login-form/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"login-form/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"login-form/js/main.js\"></script>\r\n");
      out.write("    <script src=\"login-form/js/show-fun.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
